# Generated by Django 4.2.13 on 2024-07-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_startupidea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupidea',
            options={'verbose_name': 'Startup Idea', 'verbose_name_plural': 'Startup Ideas'},
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='cold_calls_conversation',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='financial_conversation',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='general_conversation',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='market_conversation',
        ),
    ]
