# Generated by Django 4.2.13 on 2024-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_startupidea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='cold_calls_chat',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='financial_chat',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='market_chat',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='startup_chat',
            field=models.JSONField(default=list),
        ),
    ]
