# Generated by Django 4.2.13 on 2024-07-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_startupidea_cold_calls_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupidea',
            name='cold_calls_chat',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='financial_chat',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='market_chat',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='startup_chat',
        ),
    ]
