# Generated by Django 4.2.11 on 2024-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="premium_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
