# Generated by Django 4.2.13 on 2024-09-09 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_notification_options_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
