# Generated by Django 4.2.13 on 2024-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_startupidea_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
